---
- hosts: clients
  vars:
    ansible_become_pass: "password"

  tasks:
    - name: Install Firefox
      become: true
      apt:
        name: snapd
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian" and ansible_distribution_release != "jessie"
    
    - name: Install Firefox from Snap
      become: true
      shell: sudo snap install firefox
      when: ansible_os_family == "Debian"
