---
- name: Install PostgreSQL and create database
  hosts: all
  become: true
  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Install wget and ca-certificates packages
      apt:
        name:
          - wget
          - ca-certificates
        state: latest

    - name: Download PostgreSQL repository key
      get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /etc/apt/trusted.gpg.d/postgresql.asc

    - name: Add PostgreSQL repository to sources list
      shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list

    - name: Update package index
      apt:
        update_cache: yes

    - name: Install PostgreSQL and PostgreSQL-contrib packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: latest

    - name: Create PostgreSQL database
      shell: |
        sudo -u postgres psql
        CREATE DATABASE remote_med;
