---
- name: Configure the server, Download the files from Github
  hosts: database
  vars:
    ansible_become_pass: "password"
    mysql_root_password: "123"
    mysql_db_name: "remote"
    mysql_user: "sasha"
    mysql_user_password: "123"
    sql_file_path: "/home/olmo9929/remote-med.sql"  # Шлях до SQL-файлу
    mysql_bind_address: "0.0.0.0"  # Дозволяє підключення з інших IP-адрес

  tasks:
    - name: 0. Check the connection
      ping:

    - name: Ensure the directory /var/lib/apt exists
      become: true
      file:
        path: "/var/lib/apt"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure the directory /var/lib/apt/lists exists
      become: true
      file:
        path: "/var/lib/apt/lists"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure the directory /var/lib/apt/lists/partial exists
      become: true
      file:
        path: "/var/lib/apt/lists/partial"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: 1. Update Ubuntu
      become: true
      shell: apt-get update

    - name: 6. Install MySQL and create a database
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-client
        - mysql-server

    - name: 6.1.2. Install python3-mysqldb
      become: true
      apt:
        name: python3-mysqldb
        state: present

    - name: 6.2. Ensure MySQL service is running
      become: true
      service:
        name: mysql
        state: started
        enabled: yes

    - name: 6.3. Create MySQL database
      become: true
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
      vars:
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: 6.4. Create MySQL user
      become: true
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
        host: "{{ mysql_bind_address }}"
        state: present
      vars:
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: 7. Clone a public repository
      become: true
      shell: git clone https://git.mif.vu.lt/sest8864/web.git /var/www/html/web

    - name: 8. Copy remote-med.sql to the specified path
      become: true
      copy:
        src: "/var/www/html/web/remote-med.sql"
        dest: "{{ sql_file_path }}"
        remote_src: yes

    - name: 9. Load data from remote-med.sql to MySQL database
      become: true
      shell: mysql -u sasha -p{{ mysql_user_password }} -h {{ mysql_bind_address }} {{ mysql_db_name }} < {{ sql_file_path }}